// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Product struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	Description *string          `json:"description"`
	Shops       []*ProductInShop `json:"shops"`
	Image       string           `json:"image"`
}

type ProductInShop struct {
	Product   *Product `json:"Product"`
	Shop      *Shop    `json:"Shop"`
	Price     float64  `json:"price"`
	Currency  string   `json:"currency"`
	SalesUnit int      `json:"sales_unit"`
}

type Shop struct {
	ID       string           `json:"id"`
	Name     string           `json:"name"`
	Location *string          `json:"location"`
	Products []*ProductInShop `json:"products"`
}
