sources:
  - name: Orderservice
    handler:
      graphql:
        endpoint: http://localhost:4001/query
    transforms:
      - federation:
          types:
            - name: Query
              config:
                extend: true
  - name: Shopservice
    handler:
      graphql:
        endpoint: http://localhost:4002/query
    transforms:
      - federation:
          types:
            - name: Query
              config:
                extend: true
            - name: Shop
              config:
                keyFields:
                  - id
                resolveReference:
                  queryFieldName: shop
            - name: Product
              config:
                keyFields:
                  - id
                resolveReference:
                  queryFieldName: product
  - name: Customerservice
    handler:
      graphql:
        endpoint: http://localhost:4003/query
    transforms:
      - federation:
          types:
            - name: Query
              config:
                extend: true
            - name: Customer
              config:
                keyFields:
                  - id
                resolveReference:
                  queryFieldName: customer
serve:
  playground: true
